name: Update Server

on:
  push:
    branches:
      - main  # Replace with your branch name if different

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Debug Repository Information
        run: |
          echo "Repository URL: $GITHUB_REPOSITORY"
          echo "Branch Name: $GITHUB_REF"
      
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm'

      - name: Pull latest changes
        run: |
          git pull origin main > pull_changes.log
          cat pull_changes.log

      - name: Install dependencies
        run: npm i

      - name: Restart BackendAPI
        run: pm2 restart index

      - name: Restart BackendAPI
        run: pm2 save
